on:
  push:

env:
  GROUP_ID: com.octokat.app
  ARTIFACT_ID: install-octokat-app
  VERSION: 1.0-SNAPSHOT
  TARGET_GROUP_ID: com.octokat.app
  TARGET_ARTIFACT_ID: octokat-app
  TARGET_VERSION: 1.0-SNAPSHOT

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add App.java file
        run: |
          SOURCE_PATH=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          echo $SOURCE_PATH
          mkdir -p $SOURCE_PATH
          cat <<- END > $SOURCE_PATH/App.java
          package ${{ env.GROUP_ID }};
          public class App
          {
              public static void main( String[] args )
              {
                  System.out.println( "Hello from ${{ github.repository }}!" );
              }
          }
          END
        working-directory: ${{ env.ARTIFACT_ID }}

      - name: Add pom.xml with dependency
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.consumecompany.app</groupId>
            <artifactId>consume-app</artifactId>
            <version>1.0</version>
            <dependencies>
              <dependency>
                <groupId>${{ env.TARGET_GROUP_ID }}</groupId>
                <artifactId>${{ env.TARGET_ARTIFACT_ID }}</artifactId>
                <version>${{ env.TARGET_VERSION }}</version>
              </dependency>    
            </dependencies>
            <repositories>
              <repository>
                <id>github</id>
                <url>https://maven.pkg.github.com/${{ github.repository_owner }}/maven-publish</url>
              </repository>
            </repositories>
          </project>
          EOM
        working-directory: ${{ env.ARTIFACT_ID }}

      - name: Build package
        run: mvn package
        working-directory: ${{ env.ARTIFACT_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

      - name: Run package
        run: java -cp target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar ${{ env.GROUP_ID }}.App
        working-directory: ${{ env.ARTIFACT_ID }}
