on:
  push:

env:
  GROUP_ID: com.octokat.app
  ARTIFACT_ID: install-octokat-app
  VERSION: 1.0-SNAPSHOT

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create package
        run: |
          mvn archetype:generate \
            -DgroupId=${{ env.GROUP_ID }} \
            -DartifactId=${{ env.ARTIFACT_ID }} \
            -DarchetypeArtifactId=maven-archetype-quickstart \
            -Dversion=${{ env.VERSION }} \
            -DarchetypeVersion=1.4 \
            -DinteractiveMode=false \
      - name: Add App.java file
        run: |
          SOURCE_PATH=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)/App.java
          cat <<- END > $SOURCE_PATH
          package ${{ env.GROUP_ID }};
          public class App
          {
              public static void main( String[] args )
              {
                  System.out.println( "Hello from ${{ github.repository }}!" );
              }
          }
          END
        working-directory: ${{ env.ARTIFACT_ID }}

      - name: Build package
        run: mvn package
        working-directory: ${{ env.ARTIFACT_ID }}

      - name: Run package
        run: java -cp target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar ${{ env.GROUP_ID }}.App
        working-directory: ${{ env.ARTIFACT_ID }}
